### ISSUE TITLE
./Shakefile.hs ghci-tests fails

### ISSUE THREAD

**Issue by ekalosak** [swift-nav/shakers#6]
After running
`stack setup`
`stack build`
`./Shakefile.hs build-tests-error`
and passing
`./Shakefile.hs tests-error`
with `happy, lint, stack, shake, hscolor, cpphs` installed globally via cabal,

the command `./Shakefile.hs ghci-tests` fails with the error
```
Error when running Shake build system:
* ghci-tests
Error, file does not exist and no rule available:
  ghci-tests
CallStack (from HasCallStack):
  error, called at src/Development/Shake/Internal/Rules/File.hs:180:58 in shake-0.16.4-CoKadV53Xnw8afMrhudc5o:Development.Shake.Internal.Rules.File
```

presumably caused by the migration of `ghci-tests` from `Development.Shakers.stackRules` to `Development.Shakers.stackTargetRules`. The later rule is not included in the main :: IO() function in Shakefile.hs.

As an aside, the `format` argument for Shakefile.hs fails with a similar error, though it's built into the `hsRules` which _are_ included in the main :: IO() function in Shakefile.hs.

**Comment by mfine** [comment]
There are no targets rules in hitl:

https://github.com/swift-nav/shakers/blob/master/src/Development/Shakers.hs#L461

You can just use `repl` and `repl-tests`. Should really sync up "ghci" in the targets to "repl":

```
➜  ~/repos/hitl git:(master) ./Shakefile.hs repl-tests
# stack (for repl-tests)
hitl-0.0.0: initial-build-steps (lib + exe + test)
hitl-0.0.0: Test running disabled by --no-run-tests flag.
Completed 2 action(s).
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded -O2
Configuring GHCi with the following packages: hitl

* * * * * * * *
The main module to load is ambiguous. Candidates are: 
1. Package `hitl' component exe:capture-worker with main-is file: /Users/mark/repos/hitl/main/capture.hs
2. Package `hitl' component exe:metrics-worker with main-is file: /Users/mark/repos/hitl/main/metrics.hs
3. Package `hitl' component exe:passfail-worker with main-is file: /Users/mark/repos/hitl/main/passfail.hs
4. Package `hitl' component exe:plan-jobs with main-is file: /Users/mark/repos/hitl/main/plan-jobs.hs
5. Package `hitl' component exe:resolve-jobs with main-is file: /Users/mark/repos/hitl/main/resolve-jobs.hs
6. Package `hitl' component exe:schedule-jobs with main-is file: /Users/mark/repos/hitl/main/schedule-jobs.hs
7. Package `hitl' component exe:shake-hitl with main-is file: /Users/mark/repos/hitl/Shakefile.hs
8. Package `hitl' component exe:stats-worker with main-is file: /Users/mark/repos/hitl/main/stats.hs
9. Package `hitl' component test:test with main-is file: /Users/mark/repos/hitl/test/Test.hs
You can specify which one to pick by: 
 * Specifying targets to stack ghci e.g. stack ghci hitl:exe:capture-worker
 * Specifying what the main is e.g. stack ghci --main-is hitl:exe:capture-worker
 * Choosing from the candidate above [1..9]
* * * * * * * *
```

**Comment by mfine** [comment]
Just realizing that this is in the shakers repo. Yeah, the ghci ones can't be run alone - they need a target to go with them. If the name gets changed to repl, then the use case above will work, with or without a target. Sounds fine to me. Or can rename repl to ghci - either way works for me.
